
    events.listen('item.tags', function (event) {

        //Crafting
        event.get('minecraft:stone_crafting_materials').add('create:scoria_cobblestone')
        event.get('minecraft:stone_crafting_materials').add('create:dark_scoria_cobblestone')
        event.get('minecraft:stone_crafting_materials').add('create:gabbro_cobblestone')
        event.get('minecraft:stone_crafting_materials').add('create:dolomite_cobblestone')
        event.get('minecraft:stone_crafting_materials').add('create:limestone_cobblestone')
        event.get('minecraft:stone_crafting_materials').add('create:weathered_limestone_cobblestone')
        event.get('minecraft:stone_crafting_materials').add('chisel:limestone/raw')
        event.get('minecraft:stone_crafting_materials').add('chisel:marble/raw')
        event.get('faruk:dragonsteel').add('iceandfire:dragonsteel_fire_ingot')
        event.get('faruk:dragonsteel').add('iceandfire:dragonsteel_ice_ingot')
        event.get('faruk:dragonsteel').add('iceandfire:dragonsteel_lightning_ingot')
        event.get('faruk:twilight').add('twilightforest:naga_trophy')
        event.get('faruk:twilight').add('twilightforest:lich_trophy')
        event.get('faruk:twilight').add('twilightforest:minoshroom_trophy')
        event.get('faruk:twilight').add('twilightforest:hydra_trophy')
        event.get('faruk:twilight').add('twilightforest:knight_phantom_trophy')
        event.get('faruk:twilight').add('twilightforest:ur_ghast_trophy')
        event.get('faruk:twilight').add('twilightforest:yeti_trophy')
        event.get('faruk:twilight').add('twilightforest:snow_queen_trophy')
        event.get('faruk:twilight').add('twilightforest:quest_ram_trophy')

        //Remove
        event.removeAllTagsFrom('create:golden_sheet')
        event.removeAllTagsFrom('create:powdered_obsidian')
        event.removeAllTagsFrom('occultism:obsidian_dust')
        event.removeAllTagsFrom('mekanism:dust_obsidian')
        event.removeAllTagsFrom('mekanism:block_steel')
        event.removeAllTagsFrom('quark:oak_chest')
        event.removeAllTagsFrom('quark:spruce_chest')
        event.removeAllTagsFrom('quark:birch_chest')
        event.removeAllTagsFrom('quark:jungle_chest')
        event.removeAllTagsFrom('quark:acacia_chest')
        event.removeAllTagsFrom('quark:dark_oak_chest')
        event.removeAllTagsFrom('quark:crimson_chest')
        event.removeAllTagsFrom('quark:warped_chest')
        event.removeAllTagsFrom('quark:nether_brick_chest')
        event.removeAllTagsFrom('quark:purpur_chest')
        event.removeAllTagsFrom('quark:prismarine_chest')
        event.removeAllTagsFrom('quark:mushroom_chest')
        event.removeAllTagsFrom('quark:oak_trapped_chest')
        event.removeAllTagsFrom('quark:spruce_trapped_chest')
        event.removeAllTagsFrom('quark:birch_trapped_chest')
        event.removeAllTagsFrom('quark:jungle_trapped_chest')
        event.removeAllTagsFrom('quark:acacia_trapped_chest')
        event.removeAllTagsFrom('quark:dark_oak_trapped_chest')
        event.removeAllTagsFrom('quark:crimson_trapped_chest')
        event.removeAllTagsFrom('quark:warped_trapped_chest')
        event.removeAllTagsFrom('quark:nether_brick_trapped_chest')
        event.removeAllTagsFrom('quark:purpur_trapped_chest')
        event.removeAllTagsFrom('quark:prismarine_trapped_chest')
        event.removeAllTagsFrom('quark:mushroom_trapped_chest')

})