
#Dimensional shard ore generation
[worldgen]

	#Overworld
	[worldgen.overworld]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 0
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 2
		#Min height
		#Range: 0 ~ 256
		oreMin = 2
		#Max height
		#Range: 0 ~ 256
		oreMax = 40

	#Overworld
	[worldgen.nether]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 3
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 3
		#Min height
		#Range: 0 ~ 256
		oreMin = 10
		#Max height
		#Range: 0 ~ 256
		oreMax = 30

	#End
	[worldgen.end]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 4
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 4
		#Min height
		#Range: 0 ~ 256
		oreMin = 2
		#Max height
		#Range: 0 ~ 256
		oreMax = 60

