
#General settings
[general]
	#Maximum gas per operation that a normal connector can input or output
	#Range: 1 ~ 1000000000
	maxGasRateNormal = 2000
	#Maximum gas per operation that an advanced connector can input or output
	#Range: 1 ~ 1000000000
	maxGasRateAdvanced = 8000
	#Maximum infuse per operation that a normal connector can input or output
	#Range: 1 ~ 1000000000
	maxInfuseRateNormal = 2000
	#Maximum infuse per operation that an advanced connector can input or output
	#Range: 1 ~ 1000000000
	maxInfuseRateAdvanced = 8000
	#Maximum pigment per operation that a normal connector can input or output
	#Range: 1 ~ 1000000000
	maxPigmentRateNormal = 2000
	#Maximum pigment per operation that an advanced connector can input or output
	#Range: 1 ~ 1000000000
	maxPigmentRateAdvanced = 8000
	#Maximum slurry per operation that a normal connector can input or output
	#Range: 1 ~ 1000000000
	maxSlurryRateNormal = 2000
	#Maximum slurry per operation that an advanced connector can input or output
	#Range: 1 ~ 1000000000
	maxSlurryRateAdvanced = 8000

