
events.listen('recipes', function (event) {

        //Cyclic
    event.remove({id: 'cyclic:packager'})
    event.remove({id: 'cyclic:anvil_void'})
    event.remove({id: 'cyclic:chorus_flight'})
    event.remove({id: 'cyclic:prospector'})
    event.remove({id: 'cyclic:apple_sprout_diamond'})
    event.remove({id: 'cyclic:apple_sprout_emerald'})
    event.remove({id: 'cyclic:uncrafter'})
    event.remove({id: 'cyclic:disenchanter'})
    event.remove({id: 'cyclic:anvil'})
    event.remove({id: 'cyclic:anvil_magma'})
    event.remove({id: 'cyclic:magic_net'})
    event.remove({id: 'cyclic:elevation_wand'})
    event.remove({id: 'cyclic:teleport_wand'})
    event.remove({id: 'cyclic:apple_ender'})
    event.remove({id: 'cyclic:apple_lofty_stature'})
    event.remove({output: 'cyclic:apple_honey'})
    event.remove({id: 'cyclic:apple_chorus'})
    event.remove({id: 'cyclic:apple_bone'})
    event.remove({id: 'cyclic:apple_lapis'})
    event.remove({id: 'cyclic:apple_iron'})
    event.remove({id: 'cyclic:apple_diamond'})
    event.remove({id: 'cyclic:apple_emerald'})
    event.remove({id: 'cyclic:apple_chocolate'})
    event.remove({id: 'cyclic:apple_prismarine'})
    event.remove({id: 'cyclic:heart'})
    event.remove({id: 'cyclic:heart_empty'})
    event.remove({id: 'cyclic:antigravity'})
    event.remove({id: 'cyclic:ender_eye_reuse'})
    event.remove({id: 'cyclic:charm_longfall'})
    event.remove({id: 'cyclic:charm_creeper'})
    event.remove({id: 'cyclic:charm_antipotion'})
    event.remove({id: 'cyclic:charm_boostpotion'})
    event.remove({id: 'cyclic:charm_stone'})
    event.remove({id: 'cyclic:charm_crit'})
    event.remove({id: 'cyclic:quiver_damage'})
    event.remove({id: 'cyclic:quiver_lightning'})
    event.remove({id: 'cyclic:generator_fuel'})
    event.remove({id: 'cyclic:generator_food'})
    event.remove({id: 'cyclic:generator_fluid'})
    event.remove({id: 'cyclic:generator_item'})
    event.remove({id: 'cyclic:peat_generator'})
    event.remove({id: 'cyclic:battery'})
    event.remove({id: 'cyclic:charm_invisible'})
    event.remove({id: 'cyclic:charm_magicdefense'})
    event.remove({id: 'cyclic:charm_venom'})
    event.remove({id: 'cyclic:charm_water'})
    event.remove({id: 'cyclic:charm_knockback_resistance'})
    event.remove({id: 'cyclic:charm_luck'})
    event.remove({id: 'cyclic:charm_attack_speed'})
    event.remove({id: 'cyclic:ender_book'})
    event.remove({id: 'cyclic:charm_wing'})
    event.remove({id: 'cyclic:soulstone'})
    event.remove({id: 'cyclic:apple_sprout'})
    event.remove({id: 'cyclic:forester'})
    event.remove({id: 'cyclic:miner'})
    event.remove({id: 'cyclic:harvester'})
    event.remove({id: 'cyclic:cask'})
    event.remove({id: 'cyclic:tank'})
    event.remove({id: 'cyclic:shears_obsidian'})
    event.remove({id: 'cyclic:shears_flint'})
    event.remove({id: 'cyclic:charm_ultimate'})
    event.remove({id: 'cyclic:charm_void'})
    event.remove({id: 'cyclic:charm_wither'})

        //PickleTweaks
    event.remove({id: 'pickletweaks:diamond_apple'})
    event.remove({id: 'pickletweaks:emerald_apple'})
    
        //Wireless Chargers
    event.remove({id: 'wirelesschargers:advanced_wireless_block_charger'})
    event.remove({id: 'wirelesschargers:basic_wireless_block_charger'})
    event.remove({id: 'wirelesschargers:advanced_wireless_player_charger'})
    event.remove({id: 'wirelesschargers:basic_wireless_player_charger'})

        //CreateStuff&Additions
    event.remove({mod: 'create_stuff_additions'})

        //Create
    event.remove({output: 'create:rose_quartz'})
    event.remove({output: 'create:millstone'})
    event.remove({output: 'create:chromatic_compound'})
    event.remove({id: 'create:pressing/gold_ingot'})
    event.remove({id: 'emendatusenigmatica:alloy_dust/brass'})
    event.remove({output: 'create:mechanical_press'})

        //Emendatus Enigmatica
    event.remove({output: '#forge:plates', type: 'minecraft:crafting_shapeless'})
    event.remove({output: '#forge:rods/all_metal', type: 'minecraft:crafting_shapeless'})
    event.remove({output: '#forge:rods/all_metal', type: 'minecraft:crafting_shaped'})
    event.remove({id: 'createaddition:rolling/aluminum_ingot'})
    event.remove({id: 'createaddition:rolling/aluminum_plate'})
    event.remove({id: 'createaddition:rolling/steel_plate'})
    event.remove({id: 'createaddition:rolling/steel_ingot'})
    event.remove({id: 'createaddition:rolling/gold_ingot'})
    event.remove({id: 'createaddition:rolling/brass_ingot'})
    event.remove({id: 'createaddition:rolling/electrum_plate'})
    event.remove({id: 'createaddition:rolling/iron_plate'})
    event.remove({output: 'createaddition:iron_wire'})
    event.remove({output: '#forge:gears', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:enderium_dust', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:lumium_dust', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:signalum_dust', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:invar_dust', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:electrum_ingot', type: 'create:mixing'})
    event.remove({output: 'emendatusenigmatica:constantan_dust', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:constantan_ingot', type: 'create:mixing'})
    event.remove({output: 'emendatusenigmatica:copper_ingot', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:copper_ingot', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:copper_nugget', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:copper_nugget', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:silver_ingot', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:silver_ingot', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:lead_ingot', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:lead_ingot', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:tin_ingot', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:tin_ingot', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:silver_block', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:silver_block', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:lead_block', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:lead_block', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:uranium_block', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:uranium_block', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:bronze_block', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:bronze_block', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:steel_block', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:steel_block', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:steel_ingot', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:steel_ingot', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:steel_nugget', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:steel_nugget', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:silver_nugget', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:silver_nugget', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'emendatusenigmatica:lead_nugget', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'emendatusenigmatica:lead_nugget', type: 'minecraft:crafting_shaped'})
    event.remove({id: 'thermal:fire_charge/bronze_ingot_4'})
    event.remove({id: 'thermal:fire_charge/constantan_ingot_2'})
    event.remove({id: 'thermal:fire_charge/electrum_ingot_2'})
    event.remove({id: 'thermal:fire_charge/invar_ingot_3'})
    event.remove({id: 'thermal:fire_charge/signalum_ingot_4'})
    event.remove({id: 'thermal:fire_charge/lumium_ingot_4'})
    event.remove({id: 'thermal:fire_charge/enderium_ingot_2'})




        //Krate
    event.remove({output: 'krate:krate_small'})
    event.remove({output: 'krate:basic_to_big'})

        //Immersive Engineering
    event.remove({output: 'immersiveengineering:component_steel', type: 'minecraft:crafting_shaped'})
    event.remove({output: 'immersiveengineering:component_iron', type: 'minecraft:crafting_shaped'})
    event.remove({output: '#forge:wires', type: 'minecraft:crafting_shapeless'})
    event.remove({output: 'engineersdecor:small_solar_panel'})
    event.remove({output: 'immersiveengineering:capacitor_lv'})
    event.remove({output: 'immersiveengineering:capacitor_mv'})
    event.remove({output: 'immersiveengineering:capacitor_hv'})
    event.remove({output: 'immersiveengineering:rs_engineering'})
    event.remove({output: 'immersiveengineering:light_engineering'})
    event.remove({output: 'immersiveengineering:heavy_engineering'})
    event.remove({output: 'immersiveengineering:dust_hop_graphite'})
    event.remove({id: 'immersiveengineering:alloysmelter/invar'})
     
        //StorageNetworks
    event.remove({output: 'storagenetwork:master'})
    event.remove({output: 'storagenetwork:kabel'})
    event.remove({output: 'storagenetwork:inventory_remote'})
    event.remove({output: 'storagenetwork:crafting_remote'})

        //ThermalExp
    event.remove({output: 'thermal:machine_frame'})
    event.remove({id: 'thermal:machine/pulverizer/pulverizer_diamond_tools'})
    event.remove({output: 'thermal:rf_coil'})
    event.remove({output: 'thermal:redstone_servo'})
    event.remove({output: 'thermal:device_tree_extractor'})
    event.remove({output: 'thermal:rubber'})
    event.remove({id: 'thermal:machine/smelter/smelter_cured_rubber'})
    event.remove({output: 'thermal:obsidian_glass'})
    event.remove({output: '#thermal:glass/hardened', type: 'minecraft:crafting_shapeless'})
    event.remove({id: 'thermal:machine/smelter/smelter_alloy_enderium'})
    event.remove({id: 'thermal:machine/smelter/smelter_alloy_lumium'})
    event.remove({id: 'thermal:machine/smelter/smelter_alloy_signalum'})
    event.remove({id: 'thermal:smelting/cured_rubber_from_smelting'})
    event.remove({output: 'thermal:machine_furnace'})
    event.remove({output: 'thermal:machine_pulverizer'})
    event.remove({output: 'thermal:machine_smelter'})
    event.remove({output: 'thermal:machine_press'})
    event.remove({output: 'thermal:machine_pyrolyzer'})
    event.remove({output: 'thermal:machine_refinery'})
    event.remove({output: 'thermal:machine_crucible'})
    event.remove({output: 'thermal:machine_sawmill'})
    event.remove({output: 'thermal:machine_crafter'})
    event.remove({output: 'thermal:machine_insolator'})
    event.remove({output: 'thermal:phytogro'})
    event.remove({output: 'thermal:upgrade_augment_1'})
    event.remove({output: 'thermal:upgrade_augment_2'})
    event.remove({output: 'thermal:upgrade_augment_3'})
    event.remove({output: 'thermal:dynamo_stirling'})
    event.remove({output: 'thermal:dynamo_compression'})
    event.remove({output: 'thermal:dynamo_magmatic'})
    event.remove({output: 'thermal:dynamo_numismatic'})
    event.remove({output: 'thermal:dynamo_lapidary'})
    event.remove({output: 'thermal:dynamo_disenchantment'})
    event.remove({output: 'thermal:dynamo_gourmand'})
    event.remove({output: 'thermal:sugar_cane_block'})



        //Mekanism
    event.remove({output: 'mekanismgenerators:wind_generator'})
    event.remove({output: 'mekanismgenerators:gas_burning_generator'})
    event.remove({id: 'mekanism:paper'})
    event.remove({output: 'mekanismmatter:naquadah'})
    event.remove({output: 'mekanismmatter:naquadah_reactor_controller'})
    event.remove({output: 'mekanismmatter:refined_naquadah'})


        //General
    event.remove({id: 'minecraft:paper'})
    event.remove({id: 'quark:tweaks/crafting/utility/bent/paper'})
    event.remove({id: 'minecraft:sugar_from_sugar_cane'})
    event.remove({id: 'immersiveengineering:crafting/paper_from_sawdust'})
    event.remove({output: 'occultism:lenses'})
    event.remove({id:'chisel:charcoal/raw'})
    event.remove({output: 'mining_helmet:mining_helmet'})
    event.remove({output: 'occultism:obsidian_dust'})
    event.remove({output: 'mekanism:dust_obsidian'})
    event.remove({output: 'wands:stone_wand'})
    event.remove({output: 'tombstone:book_of_disenchantment'})
    

        //Industrial Foregoing
    event.remove({id: 'industrialforegoing:dryrubber'})
    event.remove({id: 'industrialforegoing:machine_frame_pity'})
    event.remove({output: 'industrialforegoing:fluid_extractor'})
    event.remove({output: 'industrialforegoing:latex_processing_unit'})
    event.remove({output: 'industrialforegoing:dissolution_chamber'})
    event.remove({output: 'industrialforegoing:latex_processing_unit'})
    event.remove({output: 'industrialforegoing:machine_frame_simple'})
    event.remove({output: 'industrialforegoing:mob_slaughter_factory'})
    event.remove({output: 'industrialforegoing:laser_drill'})
    event.remove({output: 'industrialforegoing:machine_frame_advanced'})
    event.remove({output: 'industrialforegoing:ore_laser_base'})
    event.remove({output: 'industrialforegoing:fluid_laser_base'})
    event.remove({output: 'industrialforegoing:mob_duplicator'})
    event.remove({output: 'industrialforegoing:mob_crusher'})
    event.remove({output: 'industrialforegoing:machine_frame_supreme'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon0'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon1'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon2'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon3'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon4'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon5'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon6'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon7'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon8'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon9'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon10'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/range_addon11'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/efficiency_addon_1'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/efficiency_addon_2'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/processing_addon_1'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/processing_addon_2'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/speed_addon_1'})
    event.remove({id: 'industrialforegoing:dissolution_chamber/speed_addon_2'})

    //Eidolon
    event.remove({output: 'eidolon:pewter_blend'})
    event.remove({output: 'eidolon:pewter_inlay'})
    event.remove({output: 'eidolon:gold_inlay'})
    event.remove({id: 'eidolon:blast_enchanted_ash'})
    event.remove({id: 'eidolon:enchanted_ash'})

    //Mekanism
    event.remove({id: 'mekanism:metallurgic_infusing/alloy/infused'})
    event.remove({id: 'mekanism:metallurgic_infusing/alloy/reinforced'})
    event.remove({id: 'mekanism:metallurgic_infusing/alloy/atomic'})
    event.remove({id: 'mekanism:control_circuit/basic'})
    event.remove({id: 'mekanism:control_circuit/advanced'})
    event.remove({id: 'mekanism:control_circuit/elite'})
    event.remove({id: 'mekanism:control_circuit/ultimate'})
    event.remove({id: 'mekanism:hdpe_sheet'})
    event.remove({output: 'mekanism:energized_smelter'})
    event.remove({output: 'mekanism:combiner'})
    event.remove({output: 'mekanism:osmium_compressor'})
    event.remove({output: 'mekanism:metallurgic_infuser'})
    event.remove({output: 'mekanism:enrichment_chamber'})
    event.remove({output: 'mekanism:crusher'})
    event.remove({output: 'mekanismgenerators:advanced_solar_generator'})
    event.remove({output: 'mekanism:robit'})
    event.remove({output: 'mekanism:digital_miner'})
    event.remove({output: 'mekanism:teleportation_core'})
    event.remove({output: 'mekanism:electrolytic_separator'})
    event.remove({output: 'mekanism:thermal_evaporation_block'})
    event.remove({output: 'mekanism:thermal_evaporation_controller'})
    event.remove({output: 'mekanism:chemical_infuser'})
    event.remove({output: 'mekanism:chemical_oxidizer'})
    event.remove({output: 'mekanism:chemical_washer'})
    event.remove({output: 'mekanism:boiler_casing'})
    event.remove({output: 'mekanism:induction_casing'})
    event.remove({output: 'mekanism:laser'})
    event.remove({output: 'mekanism:laser_amplifier'})
    event.remove({output: 'mekanism:solar_neutron_activator'})
    event.remove({output: 'mekanismgenerators:fusion_reactor_controller'})
    event.remove({output: 'mekanism:basic_fluid_tank'})
    event.remove({output: 'mekanismgenerators:fusion_reactor_controller'})
    event.remove({output: 'mekanismmatter:arc_furnace'})

    //Faruk
    event.remove({output: 'world_of_faruk:comp_obs'})
    event.remove({output: 'world_of_faruk:comp_obs_2'})
    event.remove({output: 'world_of_faruk:comp_obs_3'})
    event.remove({output: 'world_of_faruk:faruk_land'})

    //Ice&Fire
    event.remove({output: 'dragonseeker:dragonseeker'})
    event.remove({output: 'dragonseeker:legendary_dragonseeker'})
    event.remove({id: 'iceandfire:summoning_crystal_lightning'})
    event.remove({id: 'iceandfire:summoning_crystal_ice'})

    //Draconic
    event.remove({output: 'draconicevolution:basic_crafting_injector'})
    event.remove({output: 'draconicevolution:grinder'})
    event.remove({output: 'draconicmachinery:player_grinder'})

    //Blood Magic
    event.remove({output: 'bloodmagic:weakbloodorb'})
    event.remove({output: 'bloodmagic:apprenticebloodorb'})
    event.remove({output: 'bloodmagic:magicianbloodorb'})
    event.remove({output: 'bloodmagic:masterbloodorb'})
    event.remove({id: 'bloodmagic:arc/reversion/master_blood_orb'})
    event.remove({id: 'bloodmagic:arc/reversion/weak_blood_orb'})
    event.remove({id: 'bloodmagic:arc/reversion/apprentice_blood_orb'})
    event.remove({id: 'bloodmagic:arc/reversion/magician_blood_orb'})

    //World's best #1 Mod
    event.remove({id: 'refinedstorage:silicon'})
    event.remove({id: 'emendatusenigmatica:silicon_from_quartz/smelting/nether_quartz'})
    event.remove({id: 'refinedstorage:quartz_enriched_iron'})
    event.remove({output: 'refinedstorage:controller'})
    event.remove({output: 'extrastorage:iron_crafter'})
    event.remove({output: 'extrastorage:gold_crafter'})
    event.remove({output: 'extrastorage:diamond_crafter'})
    event.remove({output: 'extrastorage:netherite_crafter'})
    event.remove({output: 'rsinfinitybooster:dimension_card'})
    event.remove({output: 'rsinfinitybooster:infinity_card'})
    event.remove({output: 'cabletiers:elite_importer'})
    event.remove({output: 'cabletiers:ultra_importer'})
    event.remove({output: 'cabletiers:elite_exporter'})
    event.remove({output: 'cabletiers:ultra_exporter'})
    event.remove({output: 'cabletiers:creative_exporter'})
    event.remove({output: 'cabletiers:creative_importer'})
    event.remove({output: 'cabletiers:creative_constructor'})
    event.remove({output: 'cabletiers:creative_destructor'})
    event.remove({output: 'cabletiers:creative_requester'})
    event.remove({output: 'rsrequestify:requester'})

})