#Range: 1 ~ 1001
netherPyramidMaxChunkDistance = 37
#
# Average distance between spawn attempts for Repurposed Structures Pyramids.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
badlandsPyramidMaxChunkDistance = 50
#Range: 1 ~ 1001
pyramidSnowyMaxChunkDistance = 50
#Range: 1 ~ 1001
pyramidEndMaxChunkDistance = 75
#Range: 1 ~ 1001
pyramidIcyMaxChunkDistance = 45
#Range: 1 ~ 1001
pyramidJungleMaxChunkDistance = 50
#Range: 1 ~ 1001
pyramidMushroomMaxChunkDistance = 30
#Range: 1 ~ 1001
pyramidOceanMaxChunkDistance = 50
#Range: 1 ~ 1001
pyramidGiantTreeTaigaMaxChunkDistance = 50
#Range: 1 ~ 1001
pyramidFlowerForestMaxChunkDistance = 45

