#
# Average distance between spawn attempts for Repurposed Structures Temples.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
netherWastelandTempleMaxChunkDistance = 35
#Range: 1 ~ 1001
netherBasaltTempleMaxChunkDistance = 35
#Range: 1 ~ 1001
netherCrimsonTempleMaxChunkDistance = 35
#Range: 1 ~ 1001
netherWarpedTempleMaxChunkDistance = 35
#Range: 1 ~ 1001
netherSoulTempleMaxChunkDistance = 35

