#
# Average distance between spawn attempts for Repurposed Structures Witch Huts.
# 1 for spawning in most chunks and 1001 for no spawn.
#Range: 1 ~ 1001
witchHutsOakMaxChunkDistance = 64
#Range: 1 ~ 1001
witchHutsTaigaMaxChunkDistance = 64
#Range: 1 ~ 1001
witchHutsGiantTreeTaigaMaxChunkDistance = 64
#Range: 1 ~ 1001
witchHutsBirchMaxChunkDistance = 64
#Range: 1 ~ 1001
witchHutsDarkForestMaxChunkDistance = 64

